language: python
python:
- '3.6'
install:
- pip install ansible>=2.4.0 'molecule[gce]' apache-libcloud paramiko
- molecule --version
before_install:
- openssl aes-256-cbc -K $encrypted_7ca6f6f13ce7_key -iv $encrypted_7ca6f6f13ce7_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- ls -la
- env
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: pLvVUmpJrf8g/XON1ROGcGglZQpUN/c6umxbMBF1bi6/LIdzuIFW+z5nBMNXSDe3b4nZeEQiUaGl+zasTyxINuDmd0YfStpCwEmPhO5ZH4907rvhoj46Xd6wAYVX0hRQlDBy4fJnzLfKZLoMt5HYrFnWcOgzuWH52w2f8NocfnaIdXk/9fY58mOM6nFSbXiGkL2Z4TTPoynH1lQR1yBmtufDkcdy5pzs2m8vE1IRcsvDP/TZusVh+YKdzAC2uPq2MpMKi2Qw0MZ24XszPT5d3UzCJjEqrVoH+of0KWnpZlRAPY0UHIBWbNo9jtKLD5Lbu7+AI8HIJ7FSmtyRHauiMZb+3qZQk6Q35RrjZiDkZd78gPFiY3TnQvTGVdA7RMPstp/gPUs7DM8u1hw8nrD8v/WN7zaRszzd1TTA75EqjeaiY1bJq3EC2cdx4yG8ItPAoz7zePXoTrpBwYNrHjicOG3/gndCV99cuO7C5xCMsSHwx8fPYDWsXyY9gn5Wn9Ri1L/G5MKAFH8ovfiTlYKzFpavYq5RQFFj1N59wAiVGjv07op+aOu6sl+JWv3F/yRx4t7ifU1WuD3X1NmL3uBvWpWy6x+KWY4ngGVkoDS0ahiVoFqnqKZU/ZXCNp4ccSc6tfAYSdqa8U4KJ03XQc6WelWhSy1vdw9qy3sFyzfE7Xk=
  - secure: YKbdZR6xNgLwaSsJxsj6w7cQX04BjwWejt7FvmW8C7KSY3JTPfRGGM3W0ZqsbmW3WlGALr7FBm7fcmyYcpNZl1TdI9jzR70MfT67oxkSgQ3cUBfMIFNjglfi+cotH8AUhe1OmWbt2nz7m+Ft/0S77B6KLJ9ZyEN55I7CEt9g7vZ8PGpk7rdVAJgb+DCO/unmzWnz3hpbQRw5VKoIzmXoDnPXzZi6D5Ro0oK8ZQrr1wEXW1I2H7ZmNqIcLkdSuz4IExM7TNnqei3R8PPF7vUvkGwe4FFgaqEEaqJPKAHsOVPR9WhwY1Ig6L714l1eBcY3WTZDi2BC/yEsRU/ujLylh3m2GkPYgm0DsPYT+y7l6qjwsA4yzVmjaMyKQ1jap/OEoqIt39u2L7kc/N0ZsZlwC2iaRsdbj+TlESoyEqQ+hiliW4N/+BC4P7HpiaAXfYutWwRVOxxn4Qjs0FlK0pUYG2HC3SStHYgxZD7e5O2rrPlRpqdLrvxPZ//Dydq+ahZmaRAqn/D6ktFP9vOENBPBBimkpQxg6QBdvqQqSAGWIwhdo/XK//Fjo9YOlQqVIatQVHeJHo7Tu/Or1Lpgbb1i3/707+Oli4cOWP0cC3PsjowP4ziUxFbVcfh42y1vMDUNjJ1f/7njpSfobAt7v0U4R0R0Cjim4dT1C60378Xveko=
  - secure: hohZ3Wj4/7EKmsPPX7e4J5z1pgaasqDSSJcbm1j1TS+A/VeMpihrYuL1eF84h4rJbHq/OXIPRLdkQ4vA526d9blfoOdoUopMTcQg2kyO6bj80UAf/v7NA8F8pGQDPmIIw6B5psp9/B0qfEGUZmZUCytsHQ2FeNb/VIJYcGuGHAvixAsZHSAfHY+OW5/971hXWuUCUDIYrSKoPlROY8FRsAZos4I66NtMmY5YRVNCudROPqKnr8zGf1bdOVXVjmjsuyPo/QsqZgVYbRs4UnB4QOTEtAi3D33XlGCMs6pexKpupIzPsYIx/mEu6ke+6O3NnxcsdXe98ug95t+W0kGiHTvFsSDf9TXHoQziRQOsmWnZIARGG5k2ASkQtcw6Fut1rHmtojdkXfCos25vTTylKRy+tjRaV/+FB3TeR8fvirA1cLmFyjmITSSTSaZeM6W/ofSuVGsl9cFVy7q+H3LuFBuSOmhLxoVG67kUmVDCa7iFJmqrJ9c4h6Oj2oICv3792hcMNIL2menSqvMv4A9FY/xBmtXjJGgNOMJ8vLnSZWdTnGUaZ0x3tMPY6zDGTjaiC0LizkpBjm01Kp6txDu1iIQZLdwhJG2D1ZlQHRyYLxeW4CMYbkSUIsvOJ9VxvCVcQj6T4G5HoGxv7f4VF5PLVVBVnqDw43lsTLp1VOdu1rg=
notifications:
  slack:
    rooms:
      secure: TPzbPFnoFe6ZpUubcoctiK15XwyuCHPMlmOK/yK2jR9+VUEC3IO7eA5aPiaW2EWQgAq3f95vEA/UlhzuzFDV0xiUcC2u1T1gBCsjLgxow2GKpb7DQ1Tbw85pzyBr2hyeSk/YiNBSPzrI/dceX5Q5pUe+ahU7chyMq8jV4NBmLpE9tmVmVitkqCdsoV7RIfawa6MeQRXNRpz1M9wq+2aDH3R6KJTSADhLvaNq6rJ5vWHdyyEWYlGCNi3HmVOGWB8uE+RyJKxYtRRYbdGttIi7QGdKgMnMQ5jyjLoyac6zF3CyTGlhqCG7n0TTWDW5kWXuwcz/u9UW6bMxJTGqcsApLwUI/CXL7ZhVOPBJds5fsYgVFVS6UnSs7eb3tPXiNirLQs1zFCQwyXJhQyoja1MsqXAI3o0eSMiF+JUkhK8tHXHdHhgqhFfOeE05F++zW1WShq6vePwS2AfU/IoSoB51QtSoNr5gb3C0ZmbKJeBCFIjf8itLG0hvmigWFmhQ2gSzBdzfRAUz6GpvaF/BBZR7jGlSFiXrdjv9hMFDfvdXs0+h2BWlhB2G+I/gzd8O6gbzPwzy44ixOHvVmkMkS5lZnZIrsxFeCZthGNRkHlCem3H3RsCy7XFZeJvdFXrkaEiCqkWUvJ7dAmoIZbuKaPO95ZrmgynkhoRkE8nXkLXX9Qc=
