---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: instance-travis
    zone: us-central1-c
    machine_type: f1-micro
    image: ubuntu-1604-xenial-v20170919
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default    
verifier:
  name: testinfra
  lint:
    name: flake8
